#!/bin/bash
#Simple shell script to help us test the program faster ! 

echo -n "Network Scheme ([C]ircuit/[P]acket) : "
read SCHEME; SCHEME=`echo $SCHEME | tr '[:lower:]' '[:upper:]'`
if [ $SCHEME != "P" -a $SCHEME != "C" ]
then echo "Wrong input !"; exit ; fi

echo -n "Routing Scheme (SHP/SDP/LLP) : "
read ROUTE; ROUTE=`echo $ROUTE | tr '[:lower:]' '[:upper:]'`
if [ $ROUTE != "SHP" -a $ROUTE != "SDP" -a $ROUTE != "LLP" ]
then echo "Wrong input !"; exit ; fi

echo -n "Packet Rate (packets/second) : "
read RATE
if [ $RATE -le 0 ]; then echo "Only positive integers allowed !"; exit ; fi

TOP="sampletop.txt"
WORK="samplework.txt"

echo "Using files '$TOP' and '$WORK' ..."

if [ $SCHEME == "P" ]; then SCHEME="PACKET"; fi
if [ $SCHEME == "C" ]; then SCHEME="CIRCUIT"; fi
echo -e "Running python RoutingPerformance.py $SCHEME $ROUTE $TOP $WORK $RATE\n"
sleep 1

python RoutingPerformance.py $SCHEME $ROUTE $TOP $WORK $RATE

