#!/bin/bash
#Simple shell script to help us test the program faster !


#not using since we only work with Circuit now

#echo -n "Network Scheme ([C]ircuit/[P]acket) : "
#read SCHEME; SCHEME=`echo $SCHEME | tr '[:lower:]' '[:upper:]'`
#if [ $SCHEME != "P" -a $SCHEME != "C" ]
#then echo "Wrong input !"; exit ; fi

echo -n "Routing Scheme (SHP [H] /SDP [D] /LLP [L]) : "
read ROUTE; ROUTE=`echo $ROUTE | tr '[:lower:]' '[:upper:]'`


case $ROUTE in
"H") ROUTE="SHP";;
"D") ROUTE="SDP";;
"L") ROUTE="LLP";;
*)   ROUTE="SDP";;  #<--- edit this to select what default behaviour is run
esac

echo -n "Packet Rate (packets/second) : "
read RATE
if [ -z $RATE ]; then RATE=2; fi
if [ $RATE -le 0 ]; then echo "Only positive integers allowed !"; exit ; fi


if [ $# -gt 0 ]
then 
	TOP="sampletop.txt"
	WORK="samplework.txt"
else
	TOP="topology.txt"
	WORK="workload.txt"
fi

echo "Using files '$TOP' and '$WORK' ..."

#if [ $SCHEME == "P" ]; then SCHEME="PACKET"; fi
#if [ $SCHEME == "C" ]; then SCHEME="CIRCUIT"; fi

echo -e "Running python RoutingPerformance.py CIRCUIT $ROUTE $TOP $WORK $RATE\n"
sleep 1

python RoutingPerformance.py CIRCUIT $ROUTE $TOP $WORK $RATE

